name: rust

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  TOKEN: Discord-1234567890
  TEST_SERVER_ID: 1234567890
  DATABASE_URL: postgres://postgres:nameless@localhost:5432

jobs:
  rust:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v6

      - run: rustup default stable

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-1.97"

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - run: cargo fmt --check --all

      - run: cargo clippy --all

      - run: cargo nextest run --all --all-features

      - run: cargo build
