name: Sanity check (Nightly Rust)

on:
  pull_request:
  push:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - run: |
          rustup default nightly
          rustup component add rustfmt
          rustup component add clippy

      - uses: Swatinem/rust-cache@v2

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - run: cargo fmt --check --all

      - run: cargo clippy

      - run: cargo nextest run --all --all-features
