name: Sanity check

on:
  pull_request:
  push:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - run: rustup default stable

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-1.97"

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - run: cargo fmt --check --all

      - run: cargo clippy --all

      - run: cargo nextest run --all --all-features
